# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b2037719eb214a2df909f5c7fcd5f887dd4b5977e0293aba4e14b2c82f4a696d4b4788d94546e31f3c9f5606a0ead0d185ec36c5fb8a51031475125434717b5

test:
  secret_key_base: 39776ea1061bd7ce133130be2c92c90947bdc2bbd8cfedd6a3f35707c71bfd83aa20953f1b094bb6213b2b2ca30a34eb705e1edff609bc340a1a6e1b9013523f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
